### ISSUE TITLE
Thanks a lot! + warning

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [infinyte7/anki-arm64#1]
Hi,

Thanks to you I was finally able to get anki working on my pinebook pro!

The only tricky thing was that after the "pip install" the executable ended up in ~/.local/bin/anki and it took me a while to understand where it was. I am on manjaro.

Thanks a lot!

**Comment by infinyte7** [comment]
Also download this repository and copy anki.desktop to `/usr/share/applications/` and copy anki.png to `/usr/share/pixmaps/`.

Also command can be run to copy these files.

```
mv anki.desktop /usr/share/applications/anki.desktop
mv anki.png /usr/share/pixmaps/anki.png
```

It will add shortcut to open anki.

**Comment by thiswillbeyourgithub** [comment]
Thanks a lot! I think it might be worth while to add this to the readme tho.

Have a nice day.
